### ISSUE TITLE
Can't install grpc 1.24.1 with node v13.0.1

### ISSUE THREAD

**Issue by sangaman** [grpc/grpc-node#1086]
### Problem description

Travis builds are failing when trying to install grpc 1.24.1 with node v13.0.1, I've provided a snippet of the log output below.

```consoleAt global scope:

cc1plus: warning: unrecognized command line option ‘-Wno-cast-function-type’

grpc_node.target.mk:190: recipe for target 'Release/obj.target/grpc_node/ext/call.o' failed

make: *** [Release/obj.target/grpc_node/ext/call.o] Error 1

make: Leaving directory '/home/travis/build/ExchangeUnion/xud/node_modules/grpc/build'

gyp ERR! build error 

gyp ERR! stack Error: `make` failed with exit code: 2

gyp ERR! stack     at ChildProcess.onExit (/home/travis/.nvm/versions/node/v13.0.1/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)

gyp ERR! stack     at ChildProcess.emit (events.js:210:5)

gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)

gyp ERR! System Linux 4.15.0-1028-gcp

gyp ERR! command "/home/travis/.nvm/versions/node/v13.0.1/bin/node" "/home/travis/.nvm/versions/node/v13.0.1/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--library=static_library" "--module=/home/travis/build/ExchangeUnion/xud/node_modules/grpc/src/node/extension_binary/node-v79-linux-x64-glibc/grpc_node.node" "--module_name=grpc_node" "--module_path=/home/travis/build/ExchangeUnion/xud/node_modules/grpc/src/node/extension_binary/node-v79-linux-x64-glibc" "--napi_version=5" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v79"

gyp ERR! cwd /home/travis/build/ExchangeUnion/xud/node_modules/grpc

gyp ERR! node -v v13.0.1

gyp ERR! node-gyp -v v5.0.5

gyp ERR! not ok 

node-pre-gyp ERR! build error 

node-pre-gyp ERR! stack Error: Failed to execute '/home/travis/.nvm/versions/node/v13.0.1/bin/node /home/travis/.nvm/versions/node/v13.0.1/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --library=static_library --module=/home/travis/build/ExchangeUnion/xud/node_modules/grpc/src/node/extension_binary/node-v79-linux-x64-glibc/grpc_node.node --module_name=grpc_node --module_path=/home/travis/build/ExchangeUnion/xud/node_modules/grpc/src/node/extension_binary/node-v79-linux-x64-glibc --napi_version=5 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v79' (1)

node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/home/travis/build/ExchangeUnion/xud/node_modules/grpc/node_modules/node-pre-gyp/lib/util/compile.js:83:29)

node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:210:5)

node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:1028:16)

node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)

node-pre-gyp ERR! System Linux 4.15.0-1028-gcp

node-pre-gyp ERR! command "/home/travis/.nvm/versions/node/v13.0.1/bin/node" "/home/travis/build/ExchangeUnion/xud/node_modules/grpc/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build" "--library=static_library"

node-pre-gyp ERR! cwd /home/travis/build/ExchangeUnion/xud/node_modules/grpc

node-pre-gyp ERR! node -v v13.0.1

node-pre-gyp ERR! node-pre-gyp -v v0.13.0

node-pre-gyp ERR! not ok 

Failed to execute '/home/travis/.nvm/versions/node/v13.0.1/bin/node /home/travis/.nvm/versions/node/v13.0.1/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --library=static_library --module=/home/travis/build/ExchangeUnion/xud/node_modules/grpc/src/node/extension_binary/node-v79-linux-x64-glibc/grpc_node.node --module_name=grpc_node --module_path=/home/travis/build/ExchangeUnion/xud/node_modules/grpc/src/node/extension_binary/node-v79-linux-x64-glibc --napi_version=5 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v79' (1)

npm ERR! code ELIFECYCLE

npm ERR! errno 1

npm ERR! grpc@1.24.1 install: `node-pre-gyp install --fallback-to-build --library=static_library`

npm ERR! Exit status 1

npm ERR! 

npm ERR! Failed at the grpc@1.24.1 install script.

npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:

npm ERR!     /home/travis/.npm/_logs/2019-10-24T20_36_20_629Z-debug.log
```

### Reproduction steps
Run a build on Travis CI with node 13 and grpc 1.24.1.

### Environment
 - Travis build environment, Ubuntu 16.04.6 LTS
 - Node version 13.0.1
 - nvm
 - node-gyp -v v5.0.5
 - grpc 1.24.1 (also fails with 1.24.0)

**Comment by bikashsahucbnits** [comment]
DownGrade Node Version works for me... I have tried with version node version 12.13.0(Erbium)

**Comment by chayancbnits** [comment]
Try this

**Comment by ppotter100** [comment]
Had a similar problem with a Gitlab CI script here. The problem seems to be a dead link to a binary resource. Try to execute `npm install grpc@1.24.1 --build-from-source` before running `npm install`.

**Comment by murgatroid99** [comment]
The `grpc` library does not support Node 13 yet. I am working on adding support in the next version.

**Comment by murgatroid99** [comment]
I have now published grpc 1.24.2 with support for Node 13.

**Comment by JogiJosephGeorge** [comment]
My node version is 12.13.1. Still Failed at the grpc@1.24.1 install script.

**Comment by shahbazhaidry** [comment]
i still getting this problem
grpc@1.24.2 install: `node-pre-gyp install --fallback-to-build --library=static_library`
npm ERR! Exit status 1

my node version 13.5

**Comment by shubhankar30** [comment]
https://github.com/grpc/grpc-node/issues/121#issuecomment-371263503

**Comment by shubhankar30** [comment]
#issuecomment-371263503

**Comment by shubhankar30** [comment]
Please upgrade by running npm i -g firebase-tools

**Comment by wa1one** [comment]
@shubhankar30 helped me a lot
