### ISSUE TITLE
Unhandled ERR_STREAM_WRITE_AFTER_END error exception

### ISSUE THREAD

**Issue by RSATom** [grpc/grpc-node#1094]
### Environment
 - Ubuntu v19.04
 - Node v12.13
 - @grpc/grpc-js v0.6.9

### Problem description
I'm using Google Speech-To-Text (STT) with Node.js via [@google-cloud/text-to-speech](https://www.npmjs.com/package/@google-cloud/text-to-speech) (It uses `@grpc/grpc-js` under the hood) and time to time I get unhandled `ERR_STREAM_WRITE_AFTER_END` error exception when I intensively send buffers to stream created with `streamingRecognize` and ignore `write` return value (i.e don't wait `drain` event and keep sending new buffers to stream).

### Node.js console output
```
events.js:187
      throw er; // Unhandled 'error' event
      ^
Error [ERR_STREAM_WRITE_AFTER_END]: write after end
    at writeAfterEnd (_stream_writable.js:253:14)
    at ClientHttp2Stream.Writable.write (_stream_writable.js:302:5)
    at /home/user/bin/app/node_modules/@grpc/grpc-js/build/src/call-stream.js:372:34
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
Emitted 'error' event on Http2CallStream instance at:
    at errorOrDestroy (internal/streams/destroy.js:108:12)
    at onwriteError (_stream_writable.js:452:5)
    at onwrite (_stream_writable.js:473:5)
    at processTicksAndRejections (internal/process/task_queues.js:79:21) {
  code: 'ERR_STREAM_WRITE_AFTER_END'
}
```

### Investigation
After digging into sources I've found STT stream internally uses `Http2CallStream` wrapped over `ClientHttp2Stream` instance, and the problem is sometimes it's possible `ClientHttp2Stream` instance become ended (.writableEnded == true) but `Http2CallStream` instance tries send one else buffer to it. In this case `ClientHttp2Stream` instance emits `error` event, and `Http2CallStream` gets this error via write callback, and emits `error` event too. But the problem is `Http2CallStream` instance don't have `on('error', ...)` handler specified and Node just terminates application since `error` event should be handled...

### Possible solution
The solution is simple, just add empty `error` event handler to `Http2CallStream` [constructor](https://github.com/grpc/grpc-node/blob/master/packages/grpc-js/src/call-stream.ts#L132):
```
      this.on('error', (err: Error) => {
      });
```
It will "eat" error event, but `Http2CallStream` still will be able handle error via write callback.

**Comment by murgatroid99** [comment]
#1184 significantly modifies that class, and makes it no longer an event emitter, so that should resolve this issue.

**Comment by RSATom** [comment]
Thank you. Unfortunately I've totally refactored my code to avoid this problem, so can't check it any more..

**Comment by P0rth0s** [comment]
I am still seeing this issue on version 1.3.4 after upgrading to Node 14 from Node 12

`process emitted uncaught exception Error [ERR_STREAM_WRITE_AFTER_END]: write after end
at writeAfterEnd (_stream_writable.js:266:14)
at ClientHttp2Stream.Writable.write (_stream_writable.js:315:5)
at /snapshot/app/node_modules/@grpc/grpc-js/build/src/call-stream.js:593:34
at processTicksAndRejections (internal/process/task_queues.js:97:5) {
code: 'ERR_STREAM_WRITE_AFTER_END'
}`

**Comment by murgatroid99** [comment]
I have added handling for those errors in version 1.3.7.
