### ISSUE TITLE
Getting GOAWAY  error

### ISSUE THREAD

**Issue by stephenplusplus** [grpc/grpc-node#138]
_From @mkamioner on December 28, 2017 9:33_

I have been getting the following error a lot after upgrading to `0.15.0`

`Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings"`

It seems that the `grpc` module is printing it (it is the only place in my code base where this string exists) and pubsub is the only component using grpc... Anyone else having this problem? What is the impact and how can we stop it?

Thanks!
Mo

#### Environment details

  - OS: Debian 8.10, x86_64 GNU/Linux
  - Node.js version: 6.12.2
  - npm version: 3.10.10
  - @google-cloud/pubsub version: 0.16.1

#### Steps to reproduce

  1. Unsure, we are subscribing with multiple instances to a very active subscription

_Copied from original issue: googleapis/nodejs-pubsub#27_

**Comment by mkamioner** [comment]
Any update on this?

**Comment by mattxgreen** [comment]
Receiving the same

**Comment by wenbozhu** [comment]
Let's have the discussion at  googleapis/nodejs-pubsub  (which recently enabled grpc keep-alive).

**Comment by marodriguez-llbean** [comment]
I'm getting the same with version 0.16.1

**Comment by murgatroid99** [comment]
We have published 1.8.4, which includes a ping related fix that may resolve this problem.

**Comment by jonparrott** [comment]
Users are still experiencing this https://github.com/googleapis/nodejs-pubsub/issues/27#issuecomment-361609756

**Comment by murgatroid99** [comment]
Users are still experiencing this problem because pubsub has not upgraded to gRPC 1.8.4.

**Comment by baracoder** [comment]
For me the issue appeared when upgrading from 1.4 to 1.8, but keeping custom channel options. Removing the custom channel options seams to have solved it. I think it might have had something to do with the keep-alive or ping with no data settings.

**Comment by mkamioner** [comment]
@murgatroid99 see the [comment](https://github.com/googleapis/nodejs-pubsub/issues/27#issuecomment-361609756) - still not working even after upgrading to gRPC 1.8.4 - please advise.

**Comment by y-zeng** [comment]
@mkamioner Was the issue still observed after manually upgrading the pubsub gRPC dependency to 1.8.4?
  
@baracoder Could you please point to the custom channel options?

**Comment by mkamioner** [comment]
@y-zeng - unfortunately yes. I double checked the version and the error continues

**Comment by murgatroid99** [comment]
@mkamioner Can you share the output of `npm ls`, either here or in a gist?

**Comment by rdlowrey** [comment]
Apologies for reviving but I'm seeing this as well. I'm seeing it in my local development environment running against the **cloud pubsub emulator**. It looks like it happens at one hour of idle time with the the same topic publisher kept alive in-memory whether or not it's been actively used.

Will continue providing updates as I need this live in a GKE production environment in the next couple of weeks. Thanks in advance for your help.

**Environment**

- OS: Docker (`FROM node:9`)
- Node.js: v9.8.0
- npm: 5.7.1
- @google-cloud/pubsub: 0.16.5
- grpc: 1.9.1

**Trace**

```
E0320 05:05:00.368889271      46 chttp2_transport.cc:1105]   Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings"
(node:46) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 channel.error listeners added. Use emitter.setMaxListeners() to increase limit
(node:46) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 channel.ready listeners added. Use emitter.setMaxListeners() to increase limit
events.js:165
      throw er; // Unhandled 'error' event
      ^

Error: Cancelled
    at StreamProxy.onConnectionStatus (/app/node_modules/@google-cloud/pubsub/src/connection-pool.js:267:21)
    at StreamProxy.emit (events.js:180:13)
    at ClientDuplexStream.<anonymous> (/app/node_modules/google-gax/lib/streaming.js:130:17)
    at ClientDuplexStream.emit (events.js:180:13)
    at ClientDuplexStream._emitStatusIfDone (/app/node_modules/grpc/src/client.js:273:10)
    at ClientDuplexStream._readsDone (/app/node_modules/grpc/src/client.js:236:8)
    at readCallback (/app/node_modules/grpc/src/client.js:296:12)
Emitted 'error' event at:
    at ConnectionPool.<anonymous> (/app/node_modules/@google-cloud/pubsub/src/subscription.js:1039:10)
    at ConnectionPool.emit (events.js:180:13)
    at StreamProxy.onConnectionStatus (/app/node_modules/@google-cloud/pubsub/src/connection-pool.js:269:14)
    at StreamProxy.emit (events.js:180:13)
    [... lines matching original stack trace ...]
    at readCallback (/app/node_modules/grpc/src/client.js:296:12)
```

**Comment by murgatroid99** [comment]
We have published gRPC 1.10.1 with another potential fix for this problem.

**Comment by iMuFeng** [comment]
```
ERROR 88195 nodejs.unhandledRejectionError: 13 INTERNAL: GOAWAY received(api=ems.eMSAdapter.sync, code=13, INTERNAL)
    at GrpcSubClass._invokeRPC (/Users/mufeng/node_modules/egg-grpc/lib/base_grpc.js:113:17)
    at GrpcSubClass.BaseGrpc.(anonymous function) [as sync] (/Users/mufeng/node_modules/egg-grpc/lib/base_grpc.js:27:21)
    at DevController.sync_mailboxes (/Users/mufeng/app/controller/Users/mufeng.js:22:12)
    at Object.callFn (/Users/mufeng/node_modules/egg-core/lib/utils/index.js:36:21)
    at Object.classControllerMiddleware (/Users/mufeng/node_modules/egg-core/lib/loader/mixin/controller.js:84:20)
    at Object.callFn (/Users/mufeng/node_modules/egg-core/lib/utils/index.js:36:21)
    at wrappedController (/Users/mufeng/node_modules/egg-core/lib/utils/router.js:322:18)
    at dispatch (/Users/mufeng/node_modules/koa-router/node_modules/koa-compose/index.js:44:32)
    at next (/Users/mufeng/node_modules/koa-router/node_modules/koa-compose/index.js:45:18)
    at /Users/mufeng/node_modules/koa-router/lib/router.js:346:16
    at dispatch (/Users/mufeng/node_modules/koa-router/node_modules/koa-compose/index.js:44:32)
    at /Users/mufeng/node_modules/koa-router/node_modules/koa-compose/index.js:36:12
    at dispatch (/Users/mufeng/node_modules/koa-router/lib/router.js:351:31)
    at dispatch (/Users/mufeng/node_modules/koa-compose/index.js:42:32)
    at next (/Users/mufeng/node_modules/koa-compose/index.js:43:18)
code: 13
metadata: Metadata { _internal_repr: {} }
details: 'GOAWAY received'
name: 'unhandledRejectionError'
pid: 88195
hostname: mufengs MacBook-Pro.local
```

gRPC 1.10.1 also has this problem

**Comment by murgatroid99** [comment]
The fix mentioned was specifically for the "too_many_pings" error. In general, a server may choose to respond with a "GOAWAY" error for any number of reasons, and this is simply how that is surfaced.
