### ISSUE TITLE
Prebuilt binaries for v1.7.0 have incorrect permissions

### ISSUE THREAD

**Issue by rmg** [grpc/grpc-node#76]
The permissions for the prebuilt linux binaries for v1.7.0 use `0750` instead of `0755` _and_ seem to be preserving some random-ish looking uid/gid instead of using the uid/gid of the installing process.

The following were run inside a docker container (`docker run --rm -it node:8.6.0 bash`):

v1.7.0:
```
root@73ae751b8855:~# npm install grpc@1.7.0
root@73ae751b8855:~# ls -l node_modules/grpc/src/node/extension_binary/node-v57-linux-x64/
total 6468
-rwxr-x--- 1 255363 5000 6621262 Nov  1 20:12 grpc_node.node
```
v1.6.6:
```
root@73ae751b8855:~# npm install grpc@1.6.6
root@73ae751b8855:~# ls -l node_modules/grpc/src/node/extension_binary/node-v57-linux-x64/
-rwxr-xr-x 1 root root 6184072 Oct  5 19:31 grpc_node.node
```

**Comment by glesage** [comment]
Would this be what is causing `Error: Cannot find module '/app/node_modules/grpc/src/node/extension_binary/node-v57-linux-x64/grpc_node.node'` ?

**Comment by rmg** [comment]
It could definitely manifest as that, yes.

`node` may not be able to read the file which could bubble up as not loading and thus not finding.

**Comment by rmg** [comment]
The easy workaround for this is to add `--build-from-source=grpc` to your `npm install`.

**Comment by murgatroid99** [comment]
Thank you for reporting this. It looks like this was caused by changing the machine we built those files on. We should have a fix for this out today.

**Comment by Emmpa** [comment]
I spent several hours debugging a number of docker images that started having errors with rebuilding. Until PR #77 is published, I put a `dependency` in my package.json file with `"grpc": "1.6.6",`

**Comment by murgatroid99** [comment]
We have published grpc@1.7.1, which should fix this problem.

**Comment by badoet** [comment]
if 1.7.1 resolved this, @rmg  lets close this issue?

**Comment by sa-adebayo** [comment]
`grpc@1.7.1` didn't solve the problem for me, I had to go for `1.6.6` which worked as expected.

**Comment by GregorySmith92** [comment]
I haven't investigated this in depth but the `1.7.1` version did not solve the problem for me either.

**Comment by sa-adebayo** [comment]
@GregorySmith92 have you tried `grpc@1.6.6`?

**Comment by GregorySmith92** [comment]
@sa-adebayo Yeah I also used an older version to get around this problem

**Comment by murgatroid99** [comment]
I am having trouble reproducing this issue with `1.7.1. If you are experiencing this problem, please specify which binary exactly is getting downloaded. The name of the directory that directly contains the binary is what I need (for example, `node-v57-linux-x64` in the original question)

In addition, can you please try completely removing and re-installing the package, to ensure that the new binary is actually getting downloaded?

**Comment by samiq** [comment]
don't know if this is related but I'm having the same issues with windows (see #99) and this was working just fine just a few days ago and no longer is the case, which has made us stopped our CI as it broke our staging environment.
